#ifndef MCPE_OPTIMIZATION_CONFIG_H
#define MCPE_OPTIMIZATION_CONFIG_H

// Aggressive defaults for the 0.6.1 renderer. Set MCPE_POTATO_MODE=0 at
// compile time if the original visual distance/behavior is preferred.
#ifndef MCPE_POTATO_MODE
#define MCPE_POTATO_MODE 1
#endif

#if MCPE_POTATO_MODE
#define MCPE_MAX_RENDER_DISTANCE 192
#define MCPE_MAX_ENTITY_RENDER_DISTANCE_SQ (96.0f * 96.0f)
#define MCPE_MAX_PARTICLES_PER_TEXTURE 256
#define MCPE_DIRTY_SCAN_PER_FRAME 4
#define MCPE_NEAR_CHUNK_REBUILDS_PER_FRAME 1
#define MCPE_FAR_CHUNK_REBUILDS_PER_FRAME 1
#define MCPE_CHUNK_REBUILD_BUDGET_MS 3.0f
#else
#define MCPE_MAX_RENDER_DISTANCE 512
#define MCPE_MAX_ENTITY_RENDER_DISTANCE_SQ (512.0f * 512.0f)
#define MCPE_MAX_PARTICLES_PER_TEXTURE 2048
#define MCPE_DIRTY_SCAN_PER_FRAME 10
#define MCPE_NEAR_CHUNK_REBUILDS_PER_FRAME 3
#define MCPE_FAR_CHUNK_REBUILDS_PER_FRAME 3
#define MCPE_CHUNK_REBUILD_BUDGET_MS 10.0f
#endif

#endif
